version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - $HOME/mongodb/data/db2:/data/db
    networks:
      - tocos-network
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  tocos-backend:
    build: .
    image: tocos-backend:latest
    depends_on:
      - mongo
    environment:
      PORT: 3001
      LOG_LEVEL: info
      MONGODB_URI: mongodb://root:example@mongo:27017/tocos
    networks:
      - tocos-network
    ports:
      - 3001:3001

networks:
  tocos-network:
    driver: bridge